/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace vehicle
{
    public sealed class imu_measurement_t : LCM.LCM.LCMEncodable
    {
        public vehicle.header_t header;
        public vehicle.point3_t linear_acc;
        public vehicle.point3_t angular_vel;
 
        public imu_measurement_t()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0xd835a9db5b463d1dL;
 
        static imu_measurement_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("vehicle.imu_measurement_t"))
                return 0L;
 
            classes.Add("vehicle.imu_measurement_t");
            ulong hash = LCM_FINGERPRINT_BASE
                 + vehicle.header_t._hashRecursive(classes)
                 + vehicle.point3_t._hashRecursive(classes)
                 + vehicle.point3_t._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            this.header._encodeRecursive(outs); 
 
            this.linear_acc._encodeRecursive(outs); 
 
            this.angular_vel._encodeRecursive(outs); 
 
        }
 
        public imu_measurement_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public imu_measurement_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static vehicle.imu_measurement_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            vehicle.imu_measurement_t o = new vehicle.imu_measurement_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.header = vehicle.header_t._decodeRecursiveFactory(ins);
 
            this.linear_acc = vehicle.point3_t._decodeRecursiveFactory(ins);
 
            this.angular_vel = vehicle.point3_t._decodeRecursiveFactory(ins);
 
        }
 
        public vehicle.imu_measurement_t Copy()
        {
            vehicle.imu_measurement_t outobj = new vehicle.imu_measurement_t();
            outobj.header = this.header.Copy();
 
            outobj.linear_acc = this.linear_acc.Copy();
 
            outobj.angular_vel = this.angular_vel.Copy();
 
            return outobj;
        }
    }
}

